# production settings
version: "3.1"

 
services:
    node:
      image: ${DOCKER_ACCT}/simpleshelf-node-front:production
      ports:
        # Customize exported port.
        - "${NODE_PORTS}"

    couchdb:
      ports:
        # Use a single port number to disallow external access: "5984".
        - "${COUCHDB_PORTS}"
