#!/usr/bin/env bash

set -eo pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  docker compose build
  docker compose run ${TTY} "${@}"
  docker compose down
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the web container
  _dc web "${@}"
}

function secret {
  # Generate a random secret that can be used for your SECRET_KEY and more
  cmd node -e "console.log(crypto.randomBytes(64).toString('hex'));"
}

function lint:dockerfile {
  # Lint Dockerfile
  docker container run --rm -i \
    hadolint/hadolint hadolint --ignore DL3008 "${@}" - < Dockerfile
}

function lint {
  # Lint back-end
  cmd eslint "./**/*.js" "${@}"
}

function test {
  # Run back-end test suite
  cmd jest --rootDir test/ --forceExit "${@}"
}

function shell:be {
  # Start a shell session in the web container
  cmd bash "${@}"
}

function shell:fe {
  # Start a shell session in the js (development-only) container
  _dc js bash "${@}"
}

function npm:install:be {
  # Install back-end dependencies and write lock file
  _build_run_down web npm install
}

function npm:outdated:be {
  # List any installed packages that are outdated
  cmd npm outdated
}

function npm:install:fe {
  # Install front-end dependencies and write lock file
  _build_run_down js npm install
}

function npm:outdated:fe {
  # List any installed front-end packages that are outdated
  _dc js npm outdated
}

function gulp:build:app {
  # Build JS assets, this is meant to be run from within the assets container
  echo "gulp:build:app running in ${NODE_ENV}"
  if [ "${NODE_ENV}" == "production" ]; then
    gulp buildApp
  else
    gulp buildApp appWatch testWatch
  fi
}

function gulp:build:server {
  # Build server-only assets, this is meant to be run from within the assets container
  gulp buildForServer
}

function clean {
  # Remove cache and other machine generates files
  rm -rf public/*.* public/js public/css public/images public/fonts
  touch public/.keep
}

function ci:install-deps {
  # Install Continuous Integration (CI) dependencies
  sudo apt-get install -y curl shellcheck
  sudo curl \
    -L https://raw.githubusercontent.com/nickjj/wait-until/v0.2.0/wait-until \
    -o /usr/local/bin/wait-until && sudo chmod +x /usr/local/bin/wait-until
}

function ci:test {
  # Execute Continuous Integration (CI) pipeline
  #
  # It's expected that your CI environment has these tools available:
  #   - https://github.com/koalaman/shellcheck
  #   - https://github.com/nickjj/wait-until
  shellcheck run bin/*
  lint:dockerfile "${@}"

  cp --no-clobber .env.example .env
  cp --no-clobber docker-compose.override.yml.example docker-compose.override.yml

  docker compose build
  docker compose up -d

  # shellcheck disable=SC1091
  . .env
  # TODO: switch to couchdb
  wait-until "docker compose exec -T \
    -e PGPASSWORD=${POSTGRES_PASSWORD} postgres \
    psql -U ${POSTGRES_USER} ${POSTGRES_USER} -c 'SELECT 1'"

  lint "${@}"
  test "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
