# development settings, automatically overrides when using the base docker-compose.yml file
version: "3.1"
 
services:
        
    node:
      ports:
        - "${NODE_PORTS}"
      volumes:
        - ./server/code:/var/www/simpleshelf
        - ./server/config:/opt/simpleshelf/config
        - ./node_modules:/var/www/simpleshelf/node_modules
        - ./output/webapp:/var/www/simpleshelf/webapp
        - ./output/designdoc:/opt/simpleshelf/defaults/designdoc
        - ./output/docs:/opt/simpleshelf/defaults/docs
      
    couchdb:
      ports:
        # Use a single port number to disallow external access: "5984".
        - "${COUCHDB_PORTS}"
